name: test on push

on:
    push:
        branches:  [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable

            - name: build
              run: cargo build --verbose --release
            - name: run tests
              run: cargo test --verbose

